<a href="https://colab.research.google.com/github/tlswlgus960-prog/python_programming/blob/main/05_%EC%9D%B8%EA%B5%AC_%EA%B5%AC%EC%A1%B0_%ED%98%84%ED%99%A9_%EB%B6%84%EC%84%9D_%EB%B0%8F_%EC%8B%9C%EA%B0%81%ED%99%94_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

대한민국 인구 구조 현황 분석 및 시각화를 위한 실습 자료 입니다.



오늘의 실습 주제

-  주민등록 인구통계 데이터를 활용한 대한민국 인구 구조 현황 분석 및 시각화

-  https://jumin.mois.go.kr/index.jsp

- 201512_202412_주민등록인구및세대현황_연간.csv 샘플 데이터 사용

- 월간 최대 60개월까지 기간 설정 가능

- 팀별로 특정 지역을 선정하여, 지역 인구 구조 현황을 상세하게 분석



데이터셋

201512_202412_주민등록인구및세대현황_연간.csv

## 1.데이터 준비하기

###패키지 설치

설치할때에는 주석이 있으면 오류가 날수도있어서, 설치할때는 주석 작성하지않기.

In [ ]:
pip install koreanize-matplotlib

Requirement already satisfied: koreanize-matplotlib in /usr/local/lib/python3.12/dist-packages (0.1.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from koreanize-matplotlib) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize-matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize-matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize-matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize-matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize-matplotlib) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize-matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize-matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize-matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->koreanize-matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->koreanize-matplotlib) (1.17.0)

### 패키지 임포트

In [ ]:
import numpy as np
import pandas as pd
#패키지임포트

import plotly.express as px
import plotly.graph_objects as go
#패키지임포트 중 시각화..

### 데이터 불러오기

In [ ]:
df = pd.read_csv('/content/201512_202412__________________.csv', encoding='EUC-KR') #인코딩이 이유씨케이알이었으니까, 인코딩 변환해줘야함. 인코딩 기본) UTF-8
df

,행정구역,2015년_총인구수,2015년_세대수,2015년_남자 인구수,2015년_여자 인구수,2016년_총인구수,2016년_세대수,2016년_남자 인구수,2016년_여자 인구수,2017년_총인구수,...,2022년_남자 인구수,2022년_여자 인구수,2023년_총인구수,2023년_세대수,2023년_남자 인구수,2023년_여자 인구수,2024년_총인구수,2024년_세대수,2024년_남자 인구수,2024년_여자 인구수
0,전국 (1000000000),"51,529,338","21,011,152","25,758,186","25,771,152","51,696,216","21,294,009","25,827,594","25,868,622","51,778,544",...,"25,636,951","25,802,087","51,325,329","23,914,851","25,565,736","25,759,593","51,217,221","24,118,928","25,498,324","25,718,897"
1,서울특별시 (1100000000),"10,022,181","4,189,948","4,930,943","5,091,238","9,930,616","4,189,839","4,876,789","5,053,827","9,857,426",...,"4,570,048","4,858,324","9,386,034","4,469,417","4,540,031","4,846,003","9,331,828","4,482,063","4,505,355","4,826,473"
2,부산광역시 (2600000000),"3,513,777","1,437,818","1,735,570","1,778,207","3,498,529","1,451,270","1,725,607","1,772,922","3,470,653",...,"1,619,915","1,697,897","3,293,362","1,564,588","1,605,431","1,687,931","3,266,598","1,570,403","1,589,912","1,676,686"
3,대구광역시 (2700000000),"2,487,829","982,360","1,237,291","1,250,538","2,484,557","994,220","1,234,169","1,250,388","2,475,231",...,"1,162,865","1,200,826","2,374,960","1,094,148","1,166,803","1,208,157","2,363,629","1,104,130","1,159,601","1,204,028"
4,인천광역시 (2800000000),"2,925,815","1,154,004","1,469,869","1,455,946","2,943,069","1,171,399","1,477,671","1,465,398","2,948,542",...,"1,485,175","1,482,139","2,997,410","1,350,912","1,499,016","1,498,394","3,021,010","1,373,827","1,509,243","1,511,767"
5,광주광역시 (2900000000),"1,472,199","580,427","729,662","742,537","1,469,214","586,464","728,137","741,077","1,463,770",...,"707,299","723,751","1,419,237","655,433","700,896","718,341","1,408,422","658,075","695,224","713,198"
6,대전광역시 (3000000000),"1,518,775","597,008","759,778","758,997","1,514,370","606,137","757,289","757,081","1,502,227",...,"721,245","724,827","1,442,216","680,261","719,292","722,924","1,439,157","687,757","717,291","721,866"
7,울산광역시 (3100000000),"1,173,534","451,688","604,889","568,645","1,172,304","455,352","603,797","568,507","1,165,132",...,"570,368","540,295","1,103,661","490,690","567,153","536,508","1,098,049","495,378","564,888","533,161"
8,세종특별자치시 (3600000000),"210,884","81,806","105,752","105,132","243,048","94,343","121,505","121,543","280,100",...,"191,389","192,202","386,525","160,835","192,524","194,001","390,685","163,432","194,413","196,272"
9,경기도 (4100000000),"12,522,606","4,885,012","6,299,812","6,222,794","12,716,780","5,003,406","6,395,453","6,321,327","12,873,895",...,"6,839,276","6,750,156","13,630,821","5,978,724","6,855,895","6,774,926","13,694,685","6,058,202","6,882,186","6,812,499"
10,강원도 (4200000000),"1,549,507","685,005","781,434","768,073","1,550,806","692,254","781,146","769,660","1,550,142",...,"772,947","763,551",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,강원특별자치도 (5100000000),0,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,"1,527,807","760,635","768,449","759,358","1,517,766","764,834","763,025","754,741"
12,충청북도 (4300000000),"1,583,952","669,503","798,896","785,056","1,591,625","680,960","803,240","788,385","1,594,432",...,"810,782","784,276","1,593,469","779,967","810,448","783,021","1,591,177","787,756","809,920","781,257"
13,충청남도 (4400000000),"2,077,649","885,968","1,054,439","1,023,210","2,096,727","902,294","1,064,765","1,031,962","2,116,770",...,"1,086,632","1,036,405","2,130,119","1,035,449","1,091,570","1,038,549","2,136,574","1,052,129","1,096,128","1,040,446"
14,전라북도 (4500000000),"1,869,711","782,986","930,255","939,456","1,864,791","790,084","927,505","937,286","1,854,607",...,"880,592","889,015","1,754,757","861,193","873,419","881,338",NaN,NaN,NaN,NaN
15,전북특별자치도 (5200000000),0,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,"1,738,690","864,608","866,030","872,660"
16,전라남도 (4600000000),"1,908,996","833,901","953,881","955,115","1,903,914","842,688","951,889","952,025","1,896,424",...,"915,272","902,425","1,804,217","911,442","909,548","894,669","1,788,819","912,412","902,380","886,439"
17,경상북도 (4700000000),"2,702,826","1,169,648","1,357,306","1,345,520","2,700,398","1,180,643","1,356,868","1,343,530","2,691,706",...,"1,311,881","1,288,611","2,554,324","1,282,500","1,290,298","1,264,026","2,531,384","1,291,568","1,280,547","1,250,837"
18,경상남도 (4800000000),"3,364,702","1,367,142","1,694,981","1,669,721","3,373,871","1,385,684","1,699,219","1,674,652","3,380,404",...,"1,651,675","1,628,818","3,251,158","1,525,502","1,636,987","1,614,171","3,228,380","1,537,492","1,626,926","1,601,454"
19,제주특별자치도 (5000000000),"624,395","256,928","313,428","310,967","641,597","266,972","322,545","319,052","657,083",...,"339,590","338,569","675,252","313,155","337,976","337,276","670,368","314,862","335,255","335,113"

### 데이터 확인하기

In [ ]:
df.info()  #entry.들어감.입장. / non-null을 확인가능. / Dtype 보면 object로 되어있다. 숫자라고 인식을 못하고 문자로 인식(왜? 원본데이터보면, 콤마가 들어가있다. 그래서 문자로 인식 중. 숫자는 콤마 없애야 함.)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 41 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   행정구역          20 non-null     object
 1   2015년_총인구수    20 non-null     object
 2   2015년_세대수     20 non-null     object
 3   2015년_남자 인구수  20 non-null     object
 4   2015년_여자 인구수  20 non-null     object
 5   2016년_총인구수    18 non-null     object
 6   2016년_세대수     18 non-null     object
 7   2016년_남자 인구수  18 non-null     object
 8   2016년_여자 인구수  18 non-null     object
 9   2017년_총인구수    18 non-null     object
 10  2017년_세대수     18 non-null     object
 11  2017년_남자 인구수  18 non-null     object
 12  2017년_여자 인구수  18 non-null     object
 13  2018년_총인구수    18 non-null     object
 14  2018년_세대수     18 non-null     object
 15  2018년_남자 인구수  18 non-null     object
 16  2018년_여자 인구수  18 non-null     object
 17  2019년_총인구수    18 non-null     object
 18  2019년_세대수     18 non-null     object
 19  2019년_남자 인구수  18 non-null     object
 20  2019년_여자 인구수  18 non-null     object
 21  2020년_총인구수    18 non-null     object
 22  2020년_세대수     18 non-null     object
 23  2020년_남자 인구수  18 non-null     object
 24  2020년_여자 인구수  18 non-null     object
 25  2021년_총인구수    18 non-null     object
 26  2021년_세대수     18 non-null     object
 27  2021년_남자 인구수  18 non-null     object
 28  2021년_여자 인구수  18 non-null     object
 29  2022년_총인구수    18 non-null     object
 30  2022년_세대수     18 non-null     object
 31  2022년_남자 인구수  18 non-null     object
 32  2022년_여자 인구수  18 non-null     object
 33  2023년_총인구수    18 non-null     object
 34  2023년_세대수     18 non-null     object
 35  2023년_남자 인구수  18 non-null     object
 36  2023년_여자 인구수  18 non-null     object
 37  2024년_총인구수    18 non-null     object
 38  2024년_세대수     18 non-null     object
 39  2024년_남자 인구수  18 non-null     object
 40  2024년_여자 인구수  18 non-null     object
dtypes: object(41)
memory usage: 6.5+ KB

##2.행정구역과 총 인구수 데이터 분석을 위한 전처리

*   총 인구수 분석을 위해 총 인구수 컬럼만 추출
    -> 2015,2016,2017...2024 총 인구수만 추출
*   Null 데이터가 2016년부터 존재 - 확인 필요
*   인구수 데이터 타입이 object로 되어있는 부분 -> 확인했더니, 콤마가 같이 들어있음 - 처리 필요

### 필요한 컬럼명 리스트를 만들어서 정보 추출하기

In [ ]:
df.head()

,행정구역,2015년_총인구수,2015년_세대수,2015년_남자 인구수,2015년_여자 인구수,2016년_총인구수,2016년_세대수,2016년_남자 인구수,2016년_여자 인구수,2017년_총인구수,...,2022년_남자 인구수,2022년_여자 인구수,2023년_총인구수,2023년_세대수,2023년_남자 인구수,2023년_여자 인구수,2024년_총인구수,2024년_세대수,2024년_남자 인구수,2024년_여자 인구수
0,전국 (1000000000),"51,529,338","21,011,152","25,758,186","25,771,152","51,696,216","21,294,009","25,827,594","25,868,622","51,778,544",...,"25,636,951","25,802,087","51,325,329","23,914,851","25,565,736","25,759,593","51,217,221","24,118,928","25,498,324","25,718,897"
1,서울특별시 (1100000000),"10,022,181","4,189,948","4,930,943","5,091,238","9,930,616","4,189,839","4,876,789","5,053,827","9,857,426",...,"4,570,048","4,858,324","9,386,034","4,469,417","4,540,031","4,846,003","9,331,828","4,482,063","4,505,355","4,826,473"
2,부산광역시 (2600000000),"3,513,777","1,437,818","1,735,570","1,778,207","3,498,529","1,451,270","1,725,607","1,772,922","3,470,653",...,"1,619,915","1,697,897","3,293,362","1,564,588","1,605,431","1,687,931","3,266,598","1,570,403","1,589,912","1,676,686"
3,대구광역시 (2700000000),"2,487,829","982,360","1,237,291","1,250,538","2,484,557","994,220","1,234,169","1,250,388","2,475,231",...,"1,162,865","1,200,826","2,374,960","1,094,148","1,166,803","1,208,157","2,363,629","1,104,130","1,159,601","1,204,028"
4,인천광역시 (2800000000),"2,925,815","1,154,004","1,469,869","1,455,946","2,943,069","1,171,399","1,477,671","1,465,398","2,948,542",...,"1,485,175","1,482,139","2,997,410","1,350,912","1,499,016","1,498,394","3,021,010","1,373,827","1,509,243","1,511,767"

In [ ]:
#컬럼명만 추출하기 (갖고 있는 컬럼들을 다 출력해줌) index 소괄호로 감싸져있음.
df.columns

Index(['행정구역', '2015년_총인구수', '2015년_세대수', '2015년_남자 인구수', '2015년_여자 인구수',
       '2016년_총인구수', '2016년_세대수', '2016년_남자 인구수', '2016년_여자 인구수', '2017년_총인구수',
       '2017년_세대수', '2017년_남자 인구수', '2017년_여자 인구수', '2018년_총인구수', '2018년_세대수',
       '2018년_남자 인구수', '2018년_여자 인구수', '2019년_총인구수', '2019년_세대수',
       '2019년_남자 인구수', '2019년_여자 인구수', '2020년_총인구수', '2020년_세대수',
       '2020년_남자 인구수', '2020년_여자 인구수', '2021년_총인구수', '2021년_세대수',
       '2021년_남자 인구수', '2021년_여자 인구수', '2022년_총인구수', '2022년_세대수',
       '2022년_남자 인구수', '2022년_여자 인구수', '2023년_총인구수', '2023년_세대수',
       '2023년_남자 인구수', '2023년_여자 인구수', '2024년_총인구수', '2024년_세대수',
       '2024년_남자 인구수', '2024년_여자 인구수'],
      dtype='object')

In [ ]:
#컬럼명만 추출하기 (갖고 있는 컬럼들을 다 출력해줌) index 소괄호로 감싸져있음.
#  리스트 컴프리헨션으로 찢기 -> [리스트에 담을 값 for 변수 이름 im 반복할 아이템 if 조건문]
#총인구수로만 만들어줘
col_list = [x for x in df.columns if '총인구수' in x] #in 포함되는 함수. x가 총인구수 안에 들어가면 추출. / 총인구수 구하는 거 말고 세대수 구하려면 총인구수 자리에 세대수 넣으면 됨.
col_list

['2015년_총인구수',
 '2016년_총인구수',
 '2017년_총인구수',
 '2018년_총인구수',
 '2019년_총인구수',
 '2020년_총인구수',
 '2021년_총인구수',
 '2022년_총인구수',
 '2023년_총인구수',
 '2024년_총인구수']

In [ ]:
# 행정구역 컬럼 추가 / insert 새치기. 집어넣기. 내가 원하는 구역에 새치기로 집어넣는 거.
col_list.insert(0, '행정구역')
col_list

['행정구역',
 '2015년_총인구수',
 '2016년_총인구수',
 '2017년_총인구수',
 '2018년_총인구수',
 '2019년_총인구수',
 '2020년_총인구수',
 '2021년_총인구수',
 '2022년_총인구수',
 '2023년_총인구수',
 '2024년_총인구수']

### 데이터프레임 `loc()` 메소드 사용하여 특정 정보 추출하기

In [ ]:
population_df = df.loc[:, col_list] #loc[행, 열] / 숫자 다 안 쓰고 : 콜론 하나만 적으면 전체를 의미. -> 전체 행 열을 df.loc에 담아달라는 뜻.
population_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   행정구역        20 non-null     object
 1   2015년_총인구수  20 non-null     object
 2   2016년_총인구수  18 non-null     object
 3   2017년_총인구수  18 non-null     object
 4   2018년_총인구수  18 non-null     object
 5   2019년_총인구수  18 non-null     object
 6   2020년_총인구수  18 non-null     object
 7   2021년_총인구수  18 non-null     object
 8   2022년_총인구수  18 non-null     object
 9   2023년_총인구수  18 non-null     object
 10  2024년_총인구수  18 non-null     object
dtypes: object(11)
memory usage: 1.8+ KB

In [ ]:
population_df.head()

,행정구역,2015년_총인구수,2016년_총인구수,2017년_총인구수,2018년_총인구수,2019년_총인구수,2020년_총인구수,2021년_총인구수,2022년_총인구수,2023년_총인구수,2024년_총인구수
0,전국 (1000000000),"51,529,338","51,696,216","51,778,544","51,826,059","51,849,861","51,829,023","51,638,809","51,439,038","51,325,329","51,217,221"
1,서울특별시 (1100000000),"10,022,181","9,930,616","9,857,426","9,765,623","9,729,107","9,668,465","9,509,458","9,428,372","9,386,034","9,331,828"
2,부산광역시 (2600000000),"3,513,777","3,498,529","3,470,653","3,441,453","3,413,841","3,391,946","3,350,380","3,317,812","3,293,362","3,266,598"
3,대구광역시 (2700000000),"2,487,829","2,484,557","2,475,231","2,461,769","2,438,031","2,418,346","2,385,412","2,363,691","2,374,960","2,363,629"
4,인천광역시 (2800000000),"2,925,815","2,943,069","2,948,542","2,954,642","2,957,026","2,942,828","2,948,375","2,967,314","2,997,410","3,021,010"

###행정코드 삭제하기(원본 건드리지 말고,)

In [ ]:
# 전국 (1000000000) -> 전국
population_df['행정구역'] #행정구역만 보고 싶을 때

0          전국  (1000000000)
1       서울특별시  (1100000000)
2       부산광역시  (2600000000)
3       대구광역시  (2700000000)
4       인천광역시  (2800000000)
5       광주광역시  (2900000000)
6       대전광역시  (3000000000)
7       울산광역시  (3100000000)
8     세종특별자치시  (3600000000)
9         경기도  (4100000000)
10        강원도  (4200000000)
11    강원특별자치도  (5100000000)
12       충청북도  (4300000000)
13       충청남도  (4400000000)
14       전라북도  (4500000000)
15    전북특별자치도  (5200000000)
16       전라남도  (4600000000)
17       경상북도  (4700000000)
18       경상남도  (4800000000)
19    제주특별자치도  (5000000000)
Name: 행정구역, dtype: object

In [ ]:
# 전국 (1000000000) -> 전국
# population_df['행정구역'] #행정구역만 보고 싶을 때 -> 근데, 이 ()안에 번호를 지우고 싶다!
# 소괄호() 기준으로 잘라내서 앞부분의 행정명에, 앞뒤 공백을 제거하고, 이름만(행정명만) 다시 담기. - 앞에 대전광역시 / (2000) 이렇게 두 개를 잘라서, 자른 걸 다 리스트[]로 조각내서 준다.
population_df['행정구역'].str.split('(').str.get(0).str.strip() # - 행정구역에 있는 것 중에, 문자열로 변환시켜서 + (부터를 기준으로 잘라줘.split스피릿 / str.get(0) 이 인덱스를 0번째로 넣어줘!/.str.strip() 스트립! 앞 뒤 공백을 삭제해줘! / 오른쪽 공백 제거rstrip/ 왼쪽공백제거 lstrip 왼. 오.r.L

0          전국
1       서울특별시
2       부산광역시
3       대구광역시
4       인천광역시
5       광주광역시
6       대전광역시
7       울산광역시
8     세종특별자치시
9         경기도
10        강원도
11    강원특별자치도
12       충청북도
13       충청남도
14       전라북도
15    전북특별자치도
16       전라남도
17       경상북도
18       경상남도
19    제주특별자치도
Name: 행정구역, dtype: object

In [ ]:
population_df['행정구역'] = population_df['행정구역'].str.split('(').str.get(0).str.strip() # 이제 이거를 df에 담아라!

In [ ]:
population_df #population_df 이거만 꺼내서 확인해보기 -> x축과 y축이 바뀌어야 자연스럽. 행정구역이 칼럼이 되어야 읽기 편함. 나머지 인구수는 row로 변환해야함.

,행정구역,2015년_총인구수,2016년_총인구수,2017년_총인구수,2018년_총인구수,2019년_총인구수,2020년_총인구수,2021년_총인구수,2022년_총인구수,2023년_총인구수,2024년_총인구수
0,전국,"51,529,338","51,696,216","51,778,544","51,826,059","51,849,861","51,829,023","51,638,809","51,439,038","51,325,329","51,217,221"
1,서울특별시,"10,022,181","9,930,616","9,857,426","9,765,623","9,729,107","9,668,465","9,509,458","9,428,372","9,386,034","9,331,828"
2,부산광역시,"3,513,777","3,498,529","3,470,653","3,441,453","3,413,841","3,391,946","3,350,380","3,317,812","3,293,362","3,266,598"
3,대구광역시,"2,487,829","2,484,557","2,475,231","2,461,769","2,438,031","2,418,346","2,385,412","2,363,691","2,374,960","2,363,629"
4,인천광역시,"2,925,815","2,943,069","2,948,542","2,954,642","2,957,026","2,942,828","2,948,375","2,967,314","2,997,410","3,021,010"
5,광주광역시,"1,472,199","1,469,214","1,463,770","1,459,336","1,456,468","1,450,062","1,441,611","1,431,050","1,419,237","1,408,422"
6,대전광역시,"1,518,775","1,514,370","1,502,227","1,489,936","1,474,870","1,463,882","1,452,251","1,446,072","1,442,216","1,439,157"
7,울산광역시,"1,173,534","1,172,304","1,165,132","1,155,623","1,148,019","1,136,017","1,121,592","1,110,663","1,103,661","1,098,049"
8,세종특별자치시,"210,884","243,048","280,100","314,126","340,575","355,831","371,895","383,591","386,525","390,685"
9,경기도,"12,522,606","12,716,780","12,873,895","13,077,153","13,239,666","13,427,014","13,565,450","13,589,432","13,630,821","13,694,685"
10,강원도,"1,549,507","1,550,806","1,550,142","1,543,052","1,541,502","1,542,840","1,538,492","1,536,498",NaN,NaN
11,강원특별자치도,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,527,807","1,517,766"
12,충청북도,"1,583,952","1,591,625","1,594,432","1,599,252","1,600,007","1,600,837","1,597,427","1,595,058","1,593,469","1,591,177"
13,충청남도,"2,077,649","2,096,727","2,116,770","2,126,282","2,123,709","2,121,029","2,119,257","2,123,037","2,130,119","2,136,574"
14,전라북도,"1,869,711","1,864,791","1,854,607","1,836,832","1,818,917","1,804,104","1,786,855","1,769,607","1,754,757",NaN
15,전북특별자치도,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,738,690"
16,전라남도,"1,908,996","1,903,914","1,896,424","1,882,970","1,868,745","1,851,549","1,832,803","1,817,697","1,804,217","1,788,819"
17,경상북도,"2,702,826","2,700,398","2,691,706","2,676,831","2,665,836","2,639,422","2,626,609","2,600,492","2,554,324","2,531,384"
18,경상남도,"3,364,702","3,373,871","3,380,404","3,373,988","3,362,553","3,340,216","3,314,183","3,280,493","3,251,158","3,228,380"
19,제주특별자치도,"624,395","641,597","657,083","667,191","670,989","674,635","676,759","678,159","675,252","670,368"

### 행정구역을 기준으로, 행과 열을 바꾸기

set_index

In [ ]:
population_df = population_df.set_index('행정구역').T #내가 인덱스(방번호)를 다시 세팅하겠다. 행정구역을 기준으로.t=트랜스포즈 바꾼다는 이야기  transpose (순서를) 뒤바꾸다 (=reverse)/ 시각화할 때, x축이 행정구역이 되어있어야 하니까, 트랜스포즈 한 거임.(x축 = 칼럼 / y축 = row줄)

In [ ]:
population_df

행정구역,전국,서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별자치시,경기도,강원도,강원특별자치도,충청북도,충청남도,전라북도,전북특별자치도,전라남도,경상북도,경상남도,제주특별자치도
2015년_총인구수,"51,529,338","10,022,181","3,513,777","2,487,829","2,925,815","1,472,199","1,518,775","1,173,534","210,884","12,522,606","1,549,507",0,"1,583,952","2,077,649","1,869,711",0,"1,908,996","2,702,826","3,364,702","624,395"
2016년_총인구수,"51,696,216","9,930,616","3,498,529","2,484,557","2,943,069","1,469,214","1,514,370","1,172,304","243,048","12,716,780","1,550,806",NaN,"1,591,625","2,096,727","1,864,791",NaN,"1,903,914","2,700,398","3,373,871","641,597"
2017년_총인구수,"51,778,544","9,857,426","3,470,653","2,475,231","2,948,542","1,463,770","1,502,227","1,165,132","280,100","12,873,895","1,550,142",NaN,"1,594,432","2,116,770","1,854,607",NaN,"1,896,424","2,691,706","3,380,404","657,083"
2018년_총인구수,"51,826,059","9,765,623","3,441,453","2,461,769","2,954,642","1,459,336","1,489,936","1,155,623","314,126","13,077,153","1,543,052",NaN,"1,599,252","2,126,282","1,836,832",NaN,"1,882,970","2,676,831","3,373,988","667,191"
2019년_총인구수,"51,849,861","9,729,107","3,413,841","2,438,031","2,957,026","1,456,468","1,474,870","1,148,019","340,575","13,239,666","1,541,502",NaN,"1,600,007","2,123,709","1,818,917",NaN,"1,868,745","2,665,836","3,362,553","670,989"
2020년_총인구수,"51,829,023","9,668,465","3,391,946","2,418,346","2,942,828","1,450,062","1,463,882","1,136,017","355,831","13,427,014","1,542,840",NaN,"1,600,837","2,121,029","1,804,104",NaN,"1,851,549","2,639,422","3,340,216","674,635"
2021년_총인구수,"51,638,809","9,509,458","3,350,380","2,385,412","2,948,375","1,441,611","1,452,251","1,121,592","371,895","13,565,450","1,538,492",NaN,"1,597,427","2,119,257","1,786,855",NaN,"1,832,803","2,626,609","3,314,183","676,759"
2022년_총인구수,"51,439,038","9,428,372","3,317,812","2,363,691","2,967,314","1,431,050","1,446,072","1,110,663","383,591","13,589,432","1,536,498",NaN,"1,595,058","2,123,037","1,769,607",NaN,"1,817,697","2,600,492","3,280,493","678,159"
2023년_총인구수,"51,325,329","9,386,034","3,293,362","2,374,960","2,997,410","1,419,237","1,442,216","1,103,661","386,525","13,630,821",NaN,"1,527,807","1,593,469","2,130,119","1,754,757",NaN,"1,804,217","2,554,324","3,251,158","675,252"
2024년_총인구수,"51,217,221","9,331,828","3,266,598","2,363,629","3,021,010","1,408,422","1,439,157","1,098,049","390,685","13,694,685",NaN,"1,517,766","1,591,177","2,136,574",NaN,"1,738,690","1,788,819","2,531,384","3,228,380","670,368"

### 전국 컬럼 삭제(전국 데이터 삭제)

In [ ]:
population_df = population_df.drop(columns='전국') #drop 삭제하라

In [ ]:
population_df

행정구역,서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별자치시,경기도,강원도,강원특별자치도,충청북도,충청남도,전라북도,전북특별자치도,전라남도,경상북도,경상남도,제주특별자치도
2015년_총인구수,"10,022,181","3,513,777","2,487,829","2,925,815","1,472,199","1,518,775","1,173,534","210,884","12,522,606","1,549,507",0,"1,583,952","2,077,649","1,869,711",0,"1,908,996","2,702,826","3,364,702","624,395"
2016년_총인구수,"9,930,616","3,498,529","2,484,557","2,943,069","1,469,214","1,514,370","1,172,304","243,048","12,716,780","1,550,806",NaN,"1,591,625","2,096,727","1,864,791",NaN,"1,903,914","2,700,398","3,373,871","641,597"
2017년_총인구수,"9,857,426","3,470,653","2,475,231","2,948,542","1,463,770","1,502,227","1,165,132","280,100","12,873,895","1,550,142",NaN,"1,594,432","2,116,770","1,854,607",NaN,"1,896,424","2,691,706","3,380,404","657,083"
2018년_총인구수,"9,765,623","3,441,453","2,461,769","2,954,642","1,459,336","1,489,936","1,155,623","314,126","13,077,153","1,543,052",NaN,"1,599,252","2,126,282","1,836,832",NaN,"1,882,970","2,676,831","3,373,988","667,191"
2019년_총인구수,"9,729,107","3,413,841","2,438,031","2,957,026","1,456,468","1,474,870","1,148,019","340,575","13,239,666","1,541,502",NaN,"1,600,007","2,123,709","1,818,917",NaN,"1,868,745","2,665,836","3,362,553","670,989"
2020년_총인구수,"9,668,465","3,391,946","2,418,346","2,942,828","1,450,062","1,463,882","1,136,017","355,831","13,427,014","1,542,840",NaN,"1,600,837","2,121,029","1,804,104",NaN,"1,851,549","2,639,422","3,340,216","674,635"
2021년_총인구수,"9,509,458","3,350,380","2,385,412","2,948,375","1,441,611","1,452,251","1,121,592","371,895","13,565,450","1,538,492",NaN,"1,597,427","2,119,257","1,786,855",NaN,"1,832,803","2,626,609","3,314,183","676,759"
2022년_총인구수,"9,428,372","3,317,812","2,363,691","2,967,314","1,431,050","1,446,072","1,110,663","383,591","13,589,432","1,536,498",NaN,"1,595,058","2,123,037","1,769,607",NaN,"1,817,697","2,600,492","3,280,493","678,159"
2023년_총인구수,"9,386,034","3,293,362","2,374,960","2,997,410","1,419,237","1,442,216","1,103,661","386,525","13,630,821",NaN,"1,527,807","1,593,469","2,130,119","1,754,757",NaN,"1,804,217","2,554,324","3,251,158","675,252"
2024년_총인구수,"9,331,828","3,266,598","2,363,629","3,021,010","1,408,422","1,439,157","1,098,049","390,685","13,694,685",NaN,"1,517,766","1,591,177","2,136,574",NaN,"1,738,690","1,788,819","2,531,384","3,228,380","670,368"

### 총인구수 데이터 특수기호 (,콤마) 지우기 - `replace()` 메소드를 사용하여 삭제.

콤마를 없앤다음에 형변환을 해야 오류가 없음

결측치 등등 모든 오류를 다 처리한 후에, 형변환을 하는 게 순서이다. 오류가 없도록.

In [ ]:
# 특수기호(,) 삭제하기 - replace (바꾸기) 메소드
#replace(찾을 문자, 바꿀 문자, regex=True, inplace=True)
population_df.replace(',','', regex=True, inplace=True) #','콤마를 -> ''아무것도 아닌걸로 바꿔달라 -  replace(찾을 문자, 바꿀 문자) / 정규식.정규표현식. 레귤러 익스프레션의 약자. regex=True 특수기호를 나타내는 정규식. 특수기호를 뽑거나, 특수기호만 없애거나. 정규표현식을 적용해서 바꿀거다, 라는 뜻임. / inplace=True 바꾼 거 바로 적용해달라! 명령
population_df

행정구역,서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별자치시,경기도,강원도,강원특별자치도,충청북도,충청남도,전라북도,전북특별자치도,전라남도,경상북도,경상남도,제주특별자치도
2015년_총인구수,10022181,3513777,2487829,2925815,1472199,1518775,1173534,210884,12522606,1549507,0,1583952,2077649,1869711,0,1908996,2702826,3364702,624395
2016년_총인구수,9930616,3498529,2484557,2943069,1469214,1514370,1172304,243048,12716780,1550806,NaN,1591625,2096727,1864791,NaN,1903914,2700398,3373871,641597
2017년_총인구수,9857426,3470653,2475231,2948542,1463770,1502227,1165132,280100,12873895,1550142,NaN,1594432,2116770,1854607,NaN,1896424,2691706,3380404,657083
2018년_총인구수,9765623,3441453,2461769,2954642,1459336,1489936,1155623,314126,13077153,1543052,NaN,1599252,2126282,1836832,NaN,1882970,2676831,3373988,667191
2019년_총인구수,9729107,3413841,2438031,2957026,1456468,1474870,1148019,340575,13239666,1541502,NaN,1600007,2123709,1818917,NaN,1868745,2665836,3362553,670989
2020년_총인구수,9668465,3391946,2418346,2942828,1450062,1463882,1136017,355831,13427014,1542840,NaN,1600837,2121029,1804104,NaN,1851549,2639422,3340216,674635
2021년_총인구수,9509458,3350380,2385412,2948375,1441611,1452251,1121592,371895,13565450,1538492,NaN,1597427,2119257,1786855,NaN,1832803,2626609,3314183,676759
2022년_총인구수,9428372,3317812,2363691,2967314,1431050,1446072,1110663,383591,13589432,1536498,NaN,1595058,2123037,1769607,NaN,1817697,2600492,3280493,678159
2023년_총인구수,9386034,3293362,2374960,2997410,1419237,1442216,1103661,386525,13630821,NaN,1527807,1593469,2130119,1754757,NaN,1804217,2554324,3251158,675252
2024년_총인구수,9331828,3266598,2363629,3021010,1408422,1439157,1098049,390685,13694685,NaN,1517766,1591177,2136574,NaN,1738690,1788819,2531384,3228380,670368

### 결측치 (naN = not a number) 처리하기 - 공백이 아니고, 숫자 처리가 안 된 것임.

In [ ]:
#먼저, 결측치가 몇 건이나 있는지 확인부터 해야 함
population_df.isna().sum() #이즈엔에이. 트루 폴스로 진행 ->sum 다 더해. sum은 true만 더한다!

행정구역
서울특별시      0
부산광역시      0
대구광역시      0
인천광역시      0
광주광역시      0
대전광역시      0
울산광역시      0
세종특별자치시    0
경기도        0
강원도        2
강원특별자치도    7
충청북도       0
충청남도       0
전라북도       1
전북특별자치도    8
전라남도       0
경상북도       0
경상남도       0
제주특별자치도    0
dtype: int64

### 강원특별자치도와 강원도 인구수 데이터 병합하기

In [ ]:
population_df[['강원특별자치도', '강원도']] #2023년도부터 바뀐 거 확인.[]한개 확인, [[]]2개,여러개 확인. -> 강원도를 강원특별자치도로 병합시켜야겠다. 를 확인할 것.

행정구역        강원특별자치도      강원도
2015년_총인구수        0  1549507
2016년_총인구수      NaN  1550806
2017년_총인구수      NaN  1550142
2018년_총인구수      NaN  1543052
2019년_총인구수      NaN  1541502
2020년_총인구수      NaN  1542840
2021년_총인구수      NaN  1538492
2022년_총인구수      NaN  1536498
2023년_총인구수  1527807      NaN
2024년_총인구수  1517766      NaN

In [ ]:
# naN 데이터(아직 정의되지 않은 값, 연산이 불가능) 처리 -> 강원도 컬럼 데이터를 강원특별자치도 컬럼으로 통합
# 처리 순서: naN 데이터 (값을 채우거나, 값을 지우거나 해야 함) -> 형변환 -> 0으로 채우기 -> 강원도 컬럼 데이터를 강원특별자치도로 통합(더하는)

population_df['강원특별자치도'] = population_df['강원도'].astype(float).fillna(0) + population_df['강원특별자치도'].astype(float).fillna(0)  #float로 형변환(실수가 없어서, 정수로 해도되는거아닌가? -> 실수가> 정수보다 크니까, 먼저 가장 큰 범위의 실수로 변환시키고, 그 다음 정수로 변환시키는 게 좋다.) /fillna 필엔에이. 채워주는 함수 - 0으로 채워줘 / dropna() - ()로 없애줘.
population_df['강원특별자치도']
#서로 float로, 0으로 채운 후, 두개를 합치고, 합친 거를 강원특별자치도로 넣어라!

2015년_총인구수    1549507.0
2016년_총인구수    1550806.0
2017년_총인구수    1550142.0
2018년_총인구수    1543052.0
2019년_총인구수    1541502.0
2020년_총인구수    1542840.0
2021년_총인구수    1538492.0
2022년_총인구수    1536498.0
2023년_총인구수    1527807.0
2024년_총인구수    1517766.0
Name: 강원특별자치도, dtype: float64

###전북특별자치도와 전라북도 인구수 병합

In [ ]:
population_df['전북특별자치도'] = population_df['전라북도'].astype(float).fillna(0) + population_df['전북특별자치도'].astype(float).fillna(0)
population_df['전북특별자치도']

2015년_총인구수    1869711.0
2016년_총인구수    1864791.0
2017년_총인구수    1854607.0
2018년_총인구수    1836832.0
2019년_총인구수    1818917.0
2020년_총인구수    1804104.0
2021년_총인구수    1786855.0
2022년_총인구수    1769607.0
2023년_총인구수    1754757.0
2024년_총인구수    1738690.0
Name: 전북특별자치도, dtype: float64

### 필요없는 컬럼 삭제(강원도, 전라북도)

In [ ]:
population_df.drop(columns=['강원도', '전라북도'], inplace=True) #inplace=True 바꾼 거 바로 적용해 / drop 삭제하라는 함수
population_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 2015년_총인구수 to 2024년_총인구수
Data columns (total 17 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   서울특별시    10 non-null     object
 1   부산광역시    10 non-null     object
 2   대구광역시    10 non-null     object
 3   인천광역시    10 non-null     object
 4   광주광역시    10 non-null     object
 5   대전광역시    10 non-null     object
 6   울산광역시    10 non-null     object
 7   세종특별자치시  10 non-null     object
 8   경기도      10 non-null     object
 9   강원특별자치도  10 non-null     float64
 10  충청북도     10 non-null     object
 11  충청남도     10 non-null     object
 12  전북특별자치도  10 non-null     float64
 13  전라남도     10 non-null     object
 14  경상북도     10 non-null     object
 15  경상남도     10 non-null     object
 16  제주특별자치도  10 non-null     object
dtypes: float64(2), object(15)
memory usage: 1.7+ KB

In [ ]:
population_df

행정구역,서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별자치시,경기도,강원특별자치도,충청북도,충청남도,전북특별자치도,전라남도,경상북도,경상남도,제주특별자치도
2015년_총인구수,10022181,3513777,2487829,2925815,1472199,1518775,1173534,210884,12522606,1549507.0,1583952,2077649,1869711.0,1908996,2702826,3364702,624395
2016년_총인구수,9930616,3498529,2484557,2943069,1469214,1514370,1172304,243048,12716780,1550806.0,1591625,2096727,1864791.0,1903914,2700398,3373871,641597
2017년_총인구수,9857426,3470653,2475231,2948542,1463770,1502227,1165132,280100,12873895,1550142.0,1594432,2116770,1854607.0,1896424,2691706,3380404,657083
2018년_총인구수,9765623,3441453,2461769,2954642,1459336,1489936,1155623,314126,13077153,1543052.0,1599252,2126282,1836832.0,1882970,2676831,3373988,667191
2019년_총인구수,9729107,3413841,2438031,2957026,1456468,1474870,1148019,340575,13239666,1541502.0,1600007,2123709,1818917.0,1868745,2665836,3362553,670989
2020년_총인구수,9668465,3391946,2418346,2942828,1450062,1463882,1136017,355831,13427014,1542840.0,1600837,2121029,1804104.0,1851549,2639422,3340216,674635
2021년_총인구수,9509458,3350380,2385412,2948375,1441611,1452251,1121592,371895,13565450,1538492.0,1597427,2119257,1786855.0,1832803,2626609,3314183,676759
2022년_총인구수,9428372,3317812,2363691,2967314,1431050,1446072,1110663,383591,13589432,1536498.0,1595058,2123037,1769607.0,1817697,2600492,3280493,678159
2023년_총인구수,9386034,3293362,2374960,2997410,1419237,1442216,1103661,386525,13630821,1527807.0,1593469,2130119,1754757.0,1804217,2554324,3251158,675252
2024년_총인구수,9331828,3266598,2363629,3021010,1408422,1439157,1098049,390685,13694685,1517766.0,1591177,2136574,1738690.0,1788819,2531384,3228380,670368

### 인구수 정수형 데이터 타입으로 변경

In [ ]:
population_df = population_df.astype(int) #실수형을 모두 정수형으로 타입 변경!!  int 숫자형으로 형변환
population_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 2015년_총인구수 to 2024년_총인구수
Data columns (total 17 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   서울특별시    10 non-null     int64
 1   부산광역시    10 non-null     int64
 2   대구광역시    10 non-null     int64
 3   인천광역시    10 non-null     int64
 4   광주광역시    10 non-null     int64
 5   대전광역시    10 non-null     int64
 6   울산광역시    10 non-null     int64
 7   세종특별자치시  10 non-null     int64
 8   경기도      10 non-null     int64
 9   강원특별자치도  10 non-null     int64
 10  충청북도     10 non-null     int64
 11  충청남도     10 non-null     int64
 12  전북특별자치도  10 non-null     int64
 13  전라남도     10 non-null     int64
 14  경상북도     10 non-null     int64
 15  경상남도     10 non-null     int64
 16  제주특별자치도  10 non-null     int64
dtypes: int64(17)
memory usage: 1.7+ KB

In [ ]:
population_df

행정구역,서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별자치시,경기도,강원특별자치도,충청북도,충청남도,전북특별자치도,전라남도,경상북도,경상남도,제주특별자치도
2015년_총인구수,10022181,3513777,2487829,2925815,1472199,1518775,1173534,210884,12522606,1549507,1583952,2077649,1869711,1908996,2702826,3364702,624395
2016년_총인구수,9930616,3498529,2484557,2943069,1469214,1514370,1172304,243048,12716780,1550806,1591625,2096727,1864791,1903914,2700398,3373871,641597
2017년_총인구수,9857426,3470653,2475231,2948542,1463770,1502227,1165132,280100,12873895,1550142,1594432,2116770,1854607,1896424,2691706,3380404,657083
2018년_총인구수,9765623,3441453,2461769,2954642,1459336,1489936,1155623,314126,13077153,1543052,1599252,2126282,1836832,1882970,2676831,3373988,667191
2019년_총인구수,9729107,3413841,2438031,2957026,1456468,1474870,1148019,340575,13239666,1541502,1600007,2123709,1818917,1868745,2665836,3362553,670989
2020년_총인구수,9668465,3391946,2418346,2942828,1450062,1463882,1136017,355831,13427014,1542840,1600837,2121029,1804104,1851549,2639422,3340216,674635
2021년_총인구수,9509458,3350380,2385412,2948375,1441611,1452251,1121592,371895,13565450,1538492,1597427,2119257,1786855,1832803,2626609,3314183,676759
2022년_총인구수,9428372,3317812,2363691,2967314,1431050,1446072,1110663,383591,13589432,1536498,1595058,2123037,1769607,1817697,2600492,3280493,678159
2023년_총인구수,9386034,3293362,2374960,2997410,1419237,1442216,1103661,386525,13630821,1527807,1593469,2130119,1754757,1804217,2554324,3251158,675252
2024년_총인구수,9331828,3266598,2363629,3021010,1408422,1439157,1098049,390685,13694685,1517766,1591177,2136574,1738690,1788819,2531384,3228380,670368

### 전처리 완료된 인구 데이터를 저장하기

In [ ]:
population_df.to_csv('201512_202412___________________20260728.csv', #reat.csv 읽는 게 아니라. to.csv 저장할것임.(여기 안에 파일 저장명을 적기-> 기존파일명_새롭게입힌날짜.)
                     encoding = 'utf-8-sig', index_label=['연도']) #tf-8-sig이 절대 안 깨지는 인코딩언어.. / index_label=['연도'] 연도 컬럼을 따로 저장함. 0 -> 연도로 바뀜.

##3.전처리한 데이터 불러오기

In [ ]:
pop_df = pd.read_csv('/content/201512_202412___________________20260728.csv') #연도 컬럼 추가되었나 확인!
pop_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   연도       10 non-null     object
 1   서울특별시    10 non-null     int64
 2   부산광역시    10 non-null     int64
 3   대구광역시    10 non-null     int64
 4   인천광역시    10 non-null     int64
 5   광주광역시    10 non-null     int64
 6   대전광역시    10 non-null     int64
 7   울산광역시    10 non-null     int64
 8   세종특별자치시  10 non-null     int64
 9   경기도      10 non-null     int64
 10  강원특별자치도  10 non-null     int64
 11  충청북도     10 non-null     int64
 12  충청남도     10 non-null     int64
 13  전북특별자치도  10 non-null     int64
 14  전라남도     10 non-null     int64
 15  경상북도     10 non-null     int64
 16  경상남도     10 non-null     int64
 17  제주특별자치도  10 non-null     int64
dtypes: int64(17), object(1)
memory usage: 1.5+ KB

In [ ]:
pop_df.head() #head: 데이터의 머리에 있는 상위 5개 나온다.

,연도,서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별자치시,경기도,강원특별자치도,충청북도,충청남도,전북특별자치도,전라남도,경상북도,경상남도,제주특별자치도
0,2015년_총인구수,10022181,3513777,2487829,2925815,1472199,1518775,1173534,210884,12522606,1549507,1583952,2077649,1869711,1908996,2702826,3364702,624395
1,2016년_총인구수,9930616,3498529,2484557,2943069,1469214,1514370,1172304,243048,12716780,1550806,1591625,2096727,1864791,1903914,2700398,3373871,641597
2,2017년_총인구수,9857426,3470653,2475231,2948542,1463770,1502227,1165132,280100,12873895,1550142,1594432,2116770,1854607,1896424,2691706,3380404,657083
3,2018년_총인구수,9765623,3441453,2461769,2954642,1459336,1489936,1155623,314126,13077153,1543052,1599252,2126282,1836832,1882970,2676831,3373988,667191
4,2019년_총인구수,9729107,3413841,2438031,2957026,1456468,1474870,1148019,340575,13239666,1541502,1600007,2123709,1818917,1868745,2665836,3362553,670989

##4.2015-2024년 인구구조 변화 시각화

In [ ]:
# 차트 시각화 -> x축(가로, 연도) / y축(세로, 총 인구수)
# 17개 시 도의 연도별 총 인구수의 변화를 하나의 차트로 시각화

fig = go.Figure() #fig 변수명, fig도화지 한장. 17개의 시 도를 합쳐서 그려야 한다. Figure 은 대문자.

for location in pop_df.columns[1:]: #연도를 제와하고 서울특별시부터 시작하기 위해서 1: 일 부터라고 작성.
  fig.add_trace(   #trace: 추격하다 , add 더하다, 하나의 도화지에 계속 이어붙인다.
      go.Scatter(  #스캐터: x축과 y축이 만나는 지점.
          x=pop_df['연도'],
          # mode='lines',   이거 # 이거만 지우고 적으면, 점 없이 라인만 만들어줌.
          y=pop_df[location], #지역 컬럼명
          name=location #이름을 로케이션으로 만들어야 범례를 만들어줌.
      )
  )
fig.update_layout(title='대한민국 시도별 2015-2024년 총 인구수 변화') #서울,경기의 차트가 너무 상위로 차이가 나서, 나머지는 그 값이 차이가 안 나보임 -> 서울, 경기 제외 데이터도 추가로 만들면 좋다.
fig.show()

### 서울특별시 2015-2024년 총 인구수 변화 시각화

In [ ]:
fig = px.scatter(pop_df, x='연도', y='서울특별시', text='서울특별시', #데이터프레임 전체를 읽는 게 가능 / text 속성은 차트에 인구수 표현해달라는 뜻.
                 title='서울특별시 2015-2024 총 인구수 변화')
fig.show()

In [ ]:
fig = px.scatter(pop_df, x='연도', y='대구광역시', text='대구광역시', #데이터프레임 전체를 읽는 게 가능 / text 속성은 차트에 인구수 표현해달라는 뜻.
                 title='대구광역시 2015-2024 총 인구수 변화')
fig.show()

###연도별 대한민국 전체 인구 변환

17개 시 도의 인구를 합산하여 대한민군 전체 인구가 연도별로 어떻게 변화했는지 확인

In [ ]:
# 연도별 총 인구수 (17개 시도를 합친)를 집계 (새로이 만들어야 함. 모든 지역의 인구수 총합.)
# 1. 17개 시도 컬럼명 리스트
region_col = pop_df.columns.drop('연도') #연도를 빼보렴 . 지금 쓸 데이터에 연도는 안 필요해서.
region_col

# 2. 연도별, 지역별 인구를 모두 합하여 전국 인구 파생 변수를 생성
pop_df = pop_df.assign(전국인구=pop_df[region_col].sum(axis=1)) # assign: 맡기다,파견하다 _ 새 열을 만드는. 파생변수. / axis=1: 엑세스. 컬럼단위(y축끼리)로 연산하고싶어요 = 0, 연도단위로 (row단위로 x축끼리.) 연산하고싶어요 = 1
pop_df
#assign()은 기존 DataFrame의 열을 이용하여 새로운 열(파생 변수)을 추가하거나 계산된 값을 새로운 열로 만들어 반환하는 메서드

,연도,서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별자치시,경기도,강원특별자치도,충청북도,충청남도,전북특별자치도,전라남도,경상북도,경상남도,제주특별자치도,전국인구
0,2015년_총인구수,10022181,3513777,2487829,2925815,1472199,1518775,1173534,210884,12522606,1549507,1583952,2077649,1869711,1908996,2702826,3364702,624395,51529338
1,2016년_총인구수,9930616,3498529,2484557,2943069,1469214,1514370,1172304,243048,12716780,1550806,1591625,2096727,1864791,1903914,2700398,3373871,641597,51696216
2,2017년_총인구수,9857426,3470653,2475231,2948542,1463770,1502227,1165132,280100,12873895,1550142,1594432,2116770,1854607,1896424,2691706,3380404,657083,51778544
3,2018년_총인구수,9765623,3441453,2461769,2954642,1459336,1489936,1155623,314126,13077153,1543052,1599252,2126282,1836832,1882970,2676831,3373988,667191,51826059
4,2019년_총인구수,9729107,3413841,2438031,2957026,1456468,1474870,1148019,340575,13239666,1541502,1600007,2123709,1818917,1868745,2665836,3362553,670989,51849861
5,2020년_총인구수,9668465,3391946,2418346,2942828,1450062,1463882,1136017,355831,13427014,1542840,1600837,2121029,1804104,1851549,2639422,3340216,674635,51829023
6,2021년_총인구수,9509458,3350380,2385412,2948375,1441611,1452251,1121592,371895,13565450,1538492,1597427,2119257,1786855,1832803,2626609,3314183,676759,51638809
7,2022년_총인구수,9428372,3317812,2363691,2967314,1431050,1446072,1110663,383591,13589432,1536498,1595058,2123037,1769607,1817697,2600492,3280493,678159,51439038
8,2023년_총인구수,9386034,3293362,2374960,2997410,1419237,1442216,1103661,386525,13630821,1527807,1593469,2130119,1754757,1804217,2554324,3251158,675252,51325329
9,2024년_총인구수,9331828,3266598,2363629,3021010,1408422,1439157,1098049,390685,13694685,1517766,1591177,2136574,1738690,1788819,2531384,3228380,670368,51217221

In [ ]:
pop_df[['연도','전국인구']]

           연도      전국인구
0  2015년_총인구수  51529338
1  2016년_총인구수  51696216
2  2017년_총인구수  51778544
3  2018년_총인구수  51826059
4  2019년_총인구수  51849861
5  2020년_총인구수  51829023
6  2021년_총인구수  51638809
7  2022년_총인구수  51439038
8  2023년_총인구수  51325329
9  2024년_총인구수  51217221

In [ ]:
# 시각화
fig = px.line(pop_df, x='연도', y='전국인구', markers=True, title='연도별 대한민국 전체 인구 변화') #markers=True,는 point 점선
fig.show()

### 2015년 대비 2024년 지역별 인구 증강 분석하기

In [ ]:
# 2015년 데이터와 2024년 데이터를 준비해야함(y축 데이터는 냅두고, x축 데이터만 15년, 24년도꺼만 남기면 두 개를 비교하기 쉽다.)

#1. 2015년 데이터 추출하기 ()튜플로 만들어서, 수정 불가능하게 보안.
pop_2015 = (pop_df.query("연도 == '2015년_총인구수'").drop(columns=['연도', '전국인구']).T.reset_index()) #쿼리로 이것만 찾아라! 함수. / drop(columns==['연도', '전국인구'] 연도와 전국인구를 지워라. / T.reset-index() : T트랜스포 다시 바꿔. 표에 붙여놓을 인덱스 형태로. 리셋 초기화시켜. 인덱스 권한 삭제시킬게. 너네 컬럼으로 와! 인덱스는 표에 안 들어가니까, 컬럼으로 변환시킴. 그 옆에 0~10으로 인덱스 번호가 생김.

#컬럼명 정리
pop_2015.columns = ['지역', '2015년 인구'] #컬럼명 변경
pop_2015

         지역  2015년 인구
0     서울특별시  10022181
1     부산광역시   3513777
2     대구광역시   2487829
3     인천광역시   2925815
4     광주광역시   1472199
5     대전광역시   1518775
6     울산광역시   1173534
7   세종특별자치시    210884
8       경기도  12522606
9   강원특별자치도   1549507
10     충청북도   1583952
11     충청남도   2077649
12  전북특별자치도   1869711
13     전라남도   1908996
14     경상북도   2702826
15     경상남도   3364702
16  제주특별자치도    624395

In [ ]:
#2. 2024년 데이터 추출하기 ()튜플로 만들어서, 수정 불가능하게 보안.
pop_2024 = (pop_df.query("연도 == '2024년_총인구수'").drop(columns=['연도', '전국인구']).T.reset_index()) #쿼리로 이것만 찾아라! 함수. / drop(columns==['연도', '전국인구'] 연도와 전국인구를 지워라. / T.reset-index() : T트랜스포 다시 바꿔. 표에 붙여놓을 인덱스 형태로. 리셋 초기화시켜. 인덱스 권한 삭제시킬게. 너네 컬럼으로 와! 인덱스는 표에 안 들어가니까, 컬럼으로 변환시킴. 그 옆에 0~10으로 인덱스 번호가 생김.

#컬럼명 정리
pop_2024.columns = ['지역', '2024년 인구'] #컬럼명 변경
pop_2024

         지역  2024년 인구
0     서울특별시   9331828
1     부산광역시   3266598
2     대구광역시   2363629
3     인천광역시   3021010
4     광주광역시   1408422
5     대전광역시   1439157
6     울산광역시   1098049
7   세종특별자치시    390685
8       경기도  13694685
9   강원특별자치도   1517766
10     충청북도   1591177
11     충청남도   2136574
12  전북특별자치도   1738690
13     전라남도   1788819
14     경상북도   2531384
15     경상남도   3228380
16  제주특별자치도    670368

In [ ]:
# 3. 2015, 2024년 데이터 프레임 결합
pop_change = pd.merge(pop_2015, pop_2024, on='지역') #merge 멀지 두 개를 합치는 거. 기준이 있어야 함. on=지역<기준> on이 기준.
pop_change

         지역  2015년 인구  2024년 인구
0     서울특별시  10022181   9331828
1     부산광역시   3513777   3266598
2     대구광역시   2487829   2363629
3     인천광역시   2925815   3021010
4     광주광역시   1472199   1408422
5     대전광역시   1518775   1439157
6     울산광역시   1173534   1098049
7   세종특별자치시    210884    390685
8       경기도  12522606  13694685
9   강원특별자치도   1549507   1517766
10     충청북도   1583952   1591177
11     충청남도   2077649   2136574
12  전북특별자치도   1869711   1738690
13     전라남도   1908996   1788819
14     경상북도   2702826   2531384
15     경상남도   3364702   3228380
16  제주특별자치도    624395    670368

In [ ]:
#4. 인구증감을 계산하여, 파생변수 만들기 (인구증감(+,-) 추가하기)
pop_change = pop_change.assign(인구증감 = pop_change['2024년 인구'] - pop_change['2015년 인구'])
pop_change

         지역  2015년 인구  2024년 인구     인구증감
0     서울특별시  10022181   9331828  -690353
1     부산광역시   3513777   3266598  -247179
2     대구광역시   2487829   2363629  -124200
3     인천광역시   2925815   3021010    95195
4     광주광역시   1472199   1408422   -63777
5     대전광역시   1518775   1439157   -79618
6     울산광역시   1173534   1098049   -75485
7   세종특별자치시    210884    390685   179801
8       경기도  12522606  13694685  1172079
9   강원특별자치도   1549507   1517766   -31741
10     충청북도   1583952   1591177     7225
11     충청남도   2077649   2136574    58925
12  전북특별자치도   1869711   1738690  -131021
13     전라남도   1908996   1788819  -120177
14     경상북도   2702826   2531384  -171442
15     경상남도   3364702   3228380  -136322
16  제주특별자치도    624395    670368    45973

In [ ]:
# 5. 인구 증감 순으로 정렬 (데이터 기반으로 정렬 기준 세우기)
pop_change = pop_change.sort_values(by='인구증감',  ascending=False)  #ascending=False 로 해줘야 인구 증가한 순서대로 내려온다. - asc가 오름차순, desc가 내림차순./asc를 false로 하면 내림차순으로.
pop_change

         지역  2015년 인구  2024년 인구     인구증감
8       경기도  12522606  13694685  1172079
7   세종특별자치시    210884    390685   179801
3     인천광역시   2925815   3021010    95195
11     충청남도   2077649   2136574    58925
16  제주특별자치도    624395    670368    45973
10     충청북도   1583952   1591177     7225
9   강원특별자치도   1549507   1517766   -31741
4     광주광역시   1472199   1408422   -63777
6     울산광역시   1173534   1098049   -75485
5     대전광역시   1518775   1439157   -79618
13     전라남도   1908996   1788819  -120177
2     대구광역시   2487829   2363629  -124200
12  전북특별자치도   1869711   1738690  -131021
15     경상남도   3364702   3228380  -136322
14     경상북도   2702826   2531384  -171442
1     부산광역시   3513777   3266598  -247179
0     서울특별시  10022181   9331828  -690353

In [ ]:
# 6. 인구증감 시각화

#인구증감 시각화 코드

# 시각화

fig = px.bar(
    pop_change,
    x='인구증감',
    y='지역',
    orientation='h',
    title='2015년 대비 2024년 지역별 인구 증감',
    text='인구증감',
    color='인구증감',
    color_continuous_scale='RdBu' #색깔의 스케일을 조정한다. 플러스가 강하면 파랑색, 마이너스가 강하면 빨간색으로. re = red/ bu=blue
)

fig.update_layout(
    xaxis_title='인구 증감(명)',
    yaxis_title='지역',
    yaxis={'categoryorder': 'total ascending'},
    template='plotly_white',
    height=700,
    coloraxis_showscale=False
)

fig.update_traces(
    texttemplate='%{text:+,}',
    textposition='outside'
)

fig.add_vline(
    x=0,
    line_width=1,
    line_dash='dash'
)

fig.show()

### 전년 대비 인구 증감 분석

`diff()` 메서드를 사용해서 전년 대비 전국 인구가 얼마나 증가, 감소했는지 분석하기

In [ ]:
pop_df = pop_df.assign(전년대비증감=pop_df['전국인구'].diff()) #diff: 각각 전년대비 컬럼에 맞게 정리해줌. different 함수. row끼리 빼는 거. 상위 row에서 하위 row를 순서대로 빼준다.(바로 위 줄에서 바로 아래 줄을 빼는 함수.)
pop_df

,연도,서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별자치시,경기도,강원특별자치도,충청북도,충청남도,전북특별자치도,전라남도,경상북도,경상남도,제주특별자치도,전국인구,전년대비증감
0,2015년_총인구수,10022181,3513777,2487829,2925815,1472199,1518775,1173534,210884,12522606,1549507,1583952,2077649,1869711,1908996,2702826,3364702,624395,51529338,NaN
1,2016년_총인구수,9930616,3498529,2484557,2943069,1469214,1514370,1172304,243048,12716780,1550806,1591625,2096727,1864791,1903914,2700398,3373871,641597,51696216,166878.0
2,2017년_총인구수,9857426,3470653,2475231,2948542,1463770,1502227,1165132,280100,12873895,1550142,1594432,2116770,1854607,1896424,2691706,3380404,657083,51778544,82328.0
3,2018년_총인구수,9765623,3441453,2461769,2954642,1459336,1489936,1155623,314126,13077153,1543052,1599252,2126282,1836832,1882970,2676831,3373988,667191,51826059,47515.0
4,2019년_총인구수,9729107,3413841,2438031,2957026,1456468,1474870,1148019,340575,13239666,1541502,1600007,2123709,1818917,1868745,2665836,3362553,670989,51849861,23802.0
5,2020년_총인구수,9668465,3391946,2418346,2942828,1450062,1463882,1136017,355831,13427014,1542840,1600837,2121029,1804104,1851549,2639422,3340216,674635,51829023,-20838.0
6,2021년_총인구수,9509458,3350380,2385412,2948375,1441611,1452251,1121592,371895,13565450,1538492,1597427,2119257,1786855,1832803,2626609,3314183,676759,51638809,-190214.0
7,2022년_총인구수,9428372,3317812,2363691,2967314,1431050,1446072,1110663,383591,13589432,1536498,1595058,2123037,1769607,1817697,2600492,3280493,678159,51439038,-199771.0
8,2023년_총인구수,9386034,3293362,2374960,2997410,1419237,1442216,1103661,386525,13630821,1527807,1593469,2130119,1754757,1804217,2554324,3251158,675252,51325329,-113709.0
9,2024년_총인구수,9331828,3266598,2363629,3021010,1408422,1439157,1098049,390685,13694685,1517766,1591177,2136574,1738690,1788819,2531384,3228380,670368,51217221,-108108.0

In [ ]:
# 시각화하기_전년 대비 증감 시각화 (2015년부터 있던 데이터에 추가한 것.)

# 전년대비 증감 시각화
# 시각화

fig = px.bar(
    pop_df,
    x='연도',
    y='전년대비증감',
    title='전년 대비 전국 인구 증감',
    text='전년대비증감'
)

fig.update_layout(
    xaxis_title='연도',
    yaxis_title='인구 증감(명)',
    template='plotly_white'
)

fig.update_traces(
    texttemplate='%{text:+,}',
    textposition='outside'
)

fig.add_hline(
    y=0,
    line_dash='dash'
)

fig.show()

### 전국 인구의 증감율 분석
`pct_change()` 메서드를 이용하여 전년 대비 인구 증가율(%)을 분석하기

몇 명이 증가했나 잘 안 함. 몇 퍼센트 증가했나르 주로 사용함.

In [ ]:
pop_df = pop_df.assign(전년대비증감률=pop_df['전국인구'].pct_change()*100) #pct_change()*100: 퍼센트 비율을 내는 함수. 무조건 *100 해야함. 비율을 찾아야하니까. 바로 위에 diff와 같은 원리인데, 비율 계산임. 바로 상위 줄에서 하위 줄 빠진 거를 몇 % 줄었는지 비율로 확인하는 것.
pop_df

,연도,서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별자치시,경기도,...,충청북도,충청남도,전북특별자치도,전라남도,경상북도,경상남도,제주특별자치도,전국인구,전년대비증감,전년대비증감률
0,2015년_총인구수,10022181,3513777,2487829,2925815,1472199,1518775,1173534,210884,12522606,...,1583952,2077649,1869711,1908996,2702826,3364702,624395,51529338,NaN,NaN
1,2016년_총인구수,9930616,3498529,2484557,2943069,1469214,1514370,1172304,243048,12716780,...,1591625,2096727,1864791,1903914,2700398,3373871,641597,51696216,166878.0,0.323850
2,2017년_총인구수,9857426,3470653,2475231,2948542,1463770,1502227,1165132,280100,12873895,...,1594432,2116770,1854607,1896424,2691706,3380404,657083,51778544,82328.0,0.159253
3,2018년_총인구수,9765623,3441453,2461769,2954642,1459336,1489936,1155623,314126,13077153,...,1599252,2126282,1836832,1882970,2676831,3373988,667191,51826059,47515.0,0.091766
4,2019년_총인구수,9729107,3413841,2438031,2957026,1456468,1474870,1148019,340575,13239666,...,1600007,2123709,1818917,1868745,2665836,3362553,670989,51849861,23802.0,0.045927
5,2020년_총인구수,9668465,3391946,2418346,2942828,1450062,1463882,1136017,355831,13427014,...,1600837,2121029,1804104,1851549,2639422,3340216,674635,51829023,-20838.0,-0.040189
6,2021년_총인구수,9509458,3350380,2385412,2948375,1441611,1452251,1121592,371895,13565450,...,1597427,2119257,1786855,1832803,2626609,3314183,676759,51638809,-190214.0,-0.367003
7,2022년_총인구수,9428372,3317812,2363691,2967314,1431050,1446072,1110663,383591,13589432,...,1595058,2123037,1769607,1817697,2600492,3280493,678159,51439038,-199771.0,-0.386862
8,2023년_총인구수,9386034,3293362,2374960,2997410,1419237,1442216,1103661,386525,13630821,...,1593469,2130119,1754757,1804217,2554324,3251158,675252,51325329,-113709.0,-0.221056
9,2024년_총인구수,9331828,3266598,2363629,3021010,1408422,1439157,1098049,390685,13694685,...,1591177,2136574,1738690,1788819,2531384,3228380,670368,51217221,-108108.0,-0.210633

In [ ]:
# 시각화. 전년 대비 증감율.

#전년대비 증감률 시각화
# 시각화

fig = px.line(
    pop_df,
    x='연도',
    y='전년대비증감률',
    markers=True,
    title='전년 대비 전국 인구 증감률'
)

fig.update_layout(
    xaxis_title='연도',
    yaxis_title='증감률(%)',
    template='plotly_white'
)

fig.add_hline(
    y=0,
    line_dash='dash'
)

fig.show()

### 전국의 인구 이동 평균 분석
`rolling().mean()` 메서드를 이용하여 단기 변화를 줄이고 장기적인 인구 추세를 확인

이동평균=추세를 분석하는 거.

In [ ]:
pop_df = pop_df.assign(이동평균3년=pop_df['전국인구'].rolling(3).mean())  #rolling 3년치
pop_df

,연도,서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별자치시,경기도,...,충청남도,전북특별자치도,전라남도,경상북도,경상남도,제주특별자치도,전국인구,전년대비증감,전년대비증감률,이동평균3년
0,2015년_총인구수,10022181,3513777,2487829,2925815,1472199,1518775,1173534,210884,12522606,...,2077649,1869711,1908996,2702826,3364702,624395,51529338,NaN,NaN,NaN
1,2016년_총인구수,9930616,3498529,2484557,2943069,1469214,1514370,1172304,243048,12716780,...,2096727,1864791,1903914,2700398,3373871,641597,51696216,166878.0,0.323850,NaN
2,2017년_총인구수,9857426,3470653,2475231,2948542,1463770,1502227,1165132,280100,12873895,...,2116770,1854607,1896424,2691706,3380404,657083,51778544,82328.0,0.159253,5.166803e+07
3,2018년_총인구수,9765623,3441453,2461769,2954642,1459336,1489936,1155623,314126,13077153,...,2126282,1836832,1882970,2676831,3373988,667191,51826059,47515.0,0.091766,5.176694e+07
4,2019년_총인구수,9729107,3413841,2438031,2957026,1456468,1474870,1148019,340575,13239666,...,2123709,1818917,1868745,2665836,3362553,670989,51849861,23802.0,0.045927,5.181815e+07
5,2020년_총인구수,9668465,3391946,2418346,2942828,1450062,1463882,1136017,355831,13427014,...,2121029,1804104,1851549,2639422,3340216,674635,51829023,-20838.0,-0.040189,5.183498e+07
6,2021년_총인구수,9509458,3350380,2385412,2948375,1441611,1452251,1121592,371895,13565450,...,2119257,1786855,1832803,2626609,3314183,676759,51638809,-190214.0,-0.367003,5.177256e+07
7,2022년_총인구수,9428372,3317812,2363691,2967314,1431050,1446072,1110663,383591,13589432,...,2123037,1769607,1817697,2600492,3280493,678159,51439038,-199771.0,-0.386862,5.163562e+07
8,2023년_총인구수,9386034,3293362,2374960,2997410,1419237,1442216,1103661,386525,13630821,...,2130119,1754757,1804217,2554324,3251158,675252,51325329,-113709.0,-0.221056,5.146773e+07
9,2024년_총인구수,9331828,3266598,2363629,3021010,1408422,1439157,1098049,390685,13694685,...,2136574,1738690,1788819,2531384,3228380,670368,51217221,-108108.0,-0.210633,5.132720e+07

In [ ]:
#이동평균 시각화

# 시각화

fig = px.line(
    pop_df,
    x='연도',
    y=['전국인구', '이동평균3년'],
    markers=True,
    title='전국 인구와 3년 이동평균'
)

fig.update_layout(
    xaxis_title='연도',
    yaxis_title='인구수',
    template='plotly_white'
)

fig.show()

이동평균은 "추세(Trend)를 보기 위해" 사용

이번 데이터는 연도별 변동이 크지 않아 이동평균과 원본 데이터의 차이가 크지 않지만, 이동평균은 주식 가격, 일별 방문자 수, 월별 매출처럼 변동이 큰 데이터를 분석할 때 더욱 효과적으로 활용

* 데이터는 해마다 조금씩 증가하거나 감소하는 등 단기적인 변동이 발생

* 이러한 변동 때문에 전체적인 흐름을 파악하기 어려울 수 있음

* 일정 기간의 평균을 계산하여 전체적인 추세를 부드럽게 확인

* 주식 차트의 5일선, 20일선, 60일선이 모두 이동평균

대한민국 인구 구조 현황 분석 및 시각화 프로젝트 수행 내용
##5.지역별 인구 구조 현황 상세 분석 및 시각화 (팀프로젝트)

### 프로젝트 목표

지금까지 학습한 Pandas 함수와 Plotly를 활용하여 배정받은 지역의 인구 변화를 분석하고, 데이터 분석 결과를 시각화하여 지역의 인구 특성을 파악합니다.

---

### 프로젝트 수행 내용

각 팀은 하나의 지역(시·도)을 선택하여 다음 내용을 분석합니다.

#### 1. 연도별 인구 변화 분석

- 연도별 인구 변화를 확인합니다.

- 인구가 증가하는 지역인지 감소하는 지역인지 분석합니다.

- 선 그래프로 시각화합니다.

---

#### 2. 전년 대비 인구 증감 분석

- `diff()` 함수를 활용하여 전년 대비 인구 증감을 계산합니다.

- 어느 해에 인구가 가장 많이 증가하거나 감소했는지 분석합니다.

- 막대그래프로 시각화합니다.

---

#### 3. 전년 대비 인구 증감률 분석

- `pct_change()` 함수를 활용하여 전년 대비 인구 증감률(%)을 계산합니다.

- 단순 인구 변화가 아닌 비율을 기준으로 지역의 변화를 분석합니다.

- 선 그래프로 시각화합니다.

---

#### 4. 이동평균 분석

- `rolling().mean()` 함수를 활용하여 3년 이동평균을 계산합니다.

- 실제 인구 변화와 이동평균을 비교하여 장기적인 인구 변화 추세를 확인합니다.

- 선 그래프로 시각화합니다.

---

### 프로젝트 결과 정리

분석 결과를 바탕으로 다음 내용을 작성합니다.

- 우리 지역의 인구는 증가하고 있는가, 감소하고 있는가?

- 인구 변화가 가장 컸던 시기는 언제인가?

- 이동평균을 통해 확인한 장기적인 인구 추세는 어떠한가?

- 지역의 인구 변화 원인은 무엇이라고 생각하는가?

- 향후 우리 지역의 인구는 어떻게 변화할 것으로 예상하는가?

---

### 프로젝트 제출물

- 코랩 Notebook(.ipynb)에 모두 반영

- 분석 결과 그래프

- 분석 결과 및 결론(5줄 이상)

---

### 프로젝트 활용 함수

| 함수 | 활용 내용 |

|------|-----------|

| `query()` | 지역 데이터 선택 |

| `diff()` | 전년 대비 인구 증감 계산 |

| `pct_change()` | 전년 대비 인구 증감률 계산 |

| `rolling().mean()` | 3년 이동평균 계산 |

| `plotly.express` | 데이터 시각화 |